[project]
name = "moretzslmcontrol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Moretz (Fedora)", email = "moritzvaneimern@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorlog>=6.11.0",
    "heros>=0.13.3",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pillow>=12.3.0",
    "pyedid>=1.0.3",
    "pyside6>=6.11.1",
    "pywin32>=312 ; sys_platform == 'win32'",
]

[project.scripts]
moretzslmcontrol = "moretzslmcontrol.app:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]

[tool.ruff]
src = ["src"]
line-length = 100

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    #"I",
    "B",
    "UP",
    "NPY",
    "LOG",
    "G",
    "RUF",
    "ANN",
]

ignore = [
    "E501",
    "G004",
    "ANN002", # *args
    "ANN003", # **kwargs
]

exclude = ["*.ipynb"]
