"""Static client-side contracts for the remote SLM HERO."""

from __future__ import annotations

from typing import Protocol

import numpy as np
from numpy.typing import NDArray


class SessionStats(Protocol):
    submitted_count: int
    accepted_count: int
    invalid_count: int
    displayed_count: int
    latest_revision: int
    last_displayed_revision: int


class SlmHeroConnector(Protocol):
    def toggleSlmWindow(self) -> None: ...

    def enableCorrectionPattern(self, value: bool = True, update: bool = True) -> None: ...

    def enableHologramPattern(self, value: bool = True, update: bool = True) -> None: ...

    def enableModificationPattern(self, value: bool = True, update: bool = True) -> None: ...

    def enableZernikePattern(self, value: bool = True, update: bool = True) -> None: ...

    def setFlipCorrectionPatternHorizontally(self, value: bool, update: bool = True) -> None: ...

    def setFlipCorrectionPatternVertically(self, value: bool, update: bool = True) -> None: ...

    def setFlipHologramPatternHorizontally(self, value: bool, update: bool = True) -> None: ...

    def setFlipHologramPatternVertically(self, value: bool, update: bool = True) -> None: ...

    def setFlipModificationPatternHorizontally(self, value: bool, update: bool = True) -> None: ...

    def setFlipModificationPatternVertically(self, value: bool, update: bool = True) -> None: ...

    def setCorrectionPattern(self, phaseArr: NDArray[np.floating] | None, update: bool = True) -> None: ...

    def setHologramPattern(self, phaseArr: NDArray[np.floating] | None, update: bool = True) -> None: ...

    def setModificationPattern(self, phaseArr: NDArray[np.floating] | None, update: bool = True) -> None: ...

    def setZernikePattern(self, phaseArr: NDArray[np.floating] | None, update: bool = True) -> None: ...

    def getLastFrameSnapshot(self) -> tuple[int, NDArray[np.uint8]]: ...

    def getFrameIfNewer(self, last_seen_revision: int) -> tuple[int, NDArray[np.uint8] | None]: ...

    def getStatsSnapshot(self) -> SessionStats: ...

    def getPatternSnapshots(
        self,
    ) -> tuple[
        NDArray[np.float32], NDArray[np.float32], NDArray[np.float32], NDArray[np.float32], NDArray[np.float32]
    ]: ...

    def getPatternInclusion(self) -> dict[str, bool]: ...

    def getPatternFlipStates(self) -> tuple[bool, bool, bool, bool, bool, bool]: ...
